### ISSUE TITLE
Failed to add Rising Storm 2: Vietnam

### ISSUE THREAD

**Issue by Zorrototo** [dgibbs64/hlsw-fixes#11]
I tried to add Rising Storm 2: Vietnam (which is similar to Red Orchestra 2) two different way, but if fails. I first added C:\Program Files (x86)\HLSW\ico\GameType_RS2.ico then I tried:

**1)** I tried to add it as a HL2 mod like Killing Floor 2 (Killing Floor 2, Red Orchestra 2, and Rising Storm 2 are games made by same company, on same engine) line 2502 to 2506 of Games.cfg:

```
			['rs2'] = {
				['Name'] = 'Rising Storm 2';
				['URL'] = 'https://hlswfixes.com/Rising_Storm_2:_Vietnam';
				['IconName'] = 'GameType_RS2';
			};
```
but it says: https://www.dropbox.com/s/6ws4bze0b332mvm/Capture%20d%27%C3%A9cran%202017-05-11%2019.31.32.png?dl=0 and fails to start HLSW

If I delete another mod like Conan Exiles for example, and start HLSW, it works as intended and shows the RS2 icon correctly.

**2)** So I then restored original config files, and tried to add it like Red Orchestra 2 by adding same pieces of code (but of course modified for RS 2) in Games.cfg and Addons.cfg:

Games.cfg line 4362 (after RO2):
```
	['RS2'] = {
		['Name'] = 'Rising Storm 2: Vietnam';
		['URL'] = 'https://hlswfixes.com/';
		['SupportedSince'] = 'v0.0.0.1';

		['InstallPathKeys'] = {
			[] = {
				['RegKey'] = 'HKEY_LOCAL_MACHINE\Software\Valve\Steam\InstallPath';
				['FileName'] = 'steam.exe';
				['FileExists'] = 'Steamapps\common\Rising Storm 2\Binaries\Win64\VNGame.exe';
			};
		};
		['DefaultFileName'] = 'steam.exe';
		['FileNameSubDir'] = '\Binaries\Win64';

		['Manager'] = 'Steam';

		['ConnectType'] = 'URL';
		['RunningFileName'] = 'VNGame.exe';
		['Parameter'] = {
			['Password'] = vector('?password=<PASSWORD>');
			['Connect'] = vector('<CONNECTADDRPORT>');
			['Name'] = vector('?Name=<PLAYERNAME2>');
		};

		['MapList'] = {
			['Extension'] = 'roe';
			['FileDetection'] = '%.roe';
			['Type'] = 'File';
			['UnrealCache'] = '\cache\cache.ini';
		};
		['AddOns'] = 'RS2';

		['PlayerName'] = {
			['File'] = 'system\user.ini';
			['Type'] = 'Begin';
			['Param'] = 'Name=';
		};

		['Query'] = {
			['Protocol'] = {
				[] = {
					['Protocol'] = 'HL2';
					['Condition'] = 'None';
				};
			};
		};

		['Flags'] = set('Connect', 'GamersSearch');

		['IconName'] = 'GameType_RS2';
	};
```

Addons.cfg line 842 (after RO2)
```
	['RS2'] = {
		[] = {
			['Type'] = 'Ranking';
			['Name'] = 'RS2Rank';
			['LongName'] = 'Rising Storm 2 Ranking';
			//['URL'] = 'https://hlswfixes.com/Rising_Storm_2_Ranking';
			['ActiveRule'] = 'bIsRanked';
		};
		[] = {
			['Type'] = 'AntiCheatTool';
			['Name'] = 'VAC';
			['LongName'] = 'Valve Anti-Cheat';
			['URL'] = 'https://hlswfixes.com/Valve_Anti-Cheat';
			['ActiveRule'] = 'secure';
		};
	};
```

But after doing that, it says https://www.dropbox.com/s/kces1fo7x6yb9ep/Capture%20d%27%C3%A9cran%202017-05-11%2019.42.53.png?dl=0 and starts with RS2 being detected as HL2 mod, with default HL2 icon.

I also then tried to add (with the above **2)**)this bit of code to Query.cfg line 468 (after RO2):
```
		[] = {
			['SteamAppIds'] = "418460";
			['Game'] = 'RS2';

			['ChangeDir']['rs2'] = '';
		};
```

But same result as above

Am I doing something wrong or is there something that I need to do?

**Comment by Zorrototo** [comment]
Mr Gibbs please :)

**Comment by Zorrototo** [comment]
Invoking the Great Daniel Gibbs!

**Comment by dgibbs64** [comment]
Lol. Sorry I simply have not had the time to look at this yet. If its being detected as a HL2 mod that means its using source engine query. You will have to remove another game from the hl2 section as your first error states it has reached its limit of 50. This is the reason I cannot add new games to HLSW anymore.

**Comment by Zorrototo** [comment]
OK that's what I thought but I wondered if there was a possibility of increasing that limit.

So yeah it is using source engine query, like Red Orchestra 2, which is not added as a HL2 mod in HLSW that's why I tried the second method but without success. Do you know if it is still possible to add it as a 'standalone' game instead of a HL2 mod and if so why did I fail by doing the same as for Red Orchestra 2? 

For now I added it as a HL2 mod by removing another one but that would be cool to be able to add more to the project instead of deciding the one we keep, the one we remove..

Anyway, thanks for your time :)

**Comment by dgibbs64** [comment]
I have limited success with stand alone games and most have to use the HL2 mod. RO2 may be using an older engine to RS2 that may be the issue. Since I dont have the source code for HLSW I cannot change the limit booo!!! The only way can see to do it is to comment out less popular games and have a tutorial on how to swap them around as required. Could you post your final changes or pull request them and I will add it. :)
