### ISSUE TITLE
CSGO fix

### ISSUE THREAD

**Issue by jffz** [dgibbs64/hlsw-fixes#2]
In Game.cfg, line 2426, replace 'T' by 'TERRORIST'

**Comment by dgibbs64** [comment]
What does this fix?

**Comment by jffz** [comment]
Color in logs

**Comment by dgibbs64** [comment]
OK does the same alloy for the other Counter Strike games or just CS:GO?

**Comment by jffz** [comment]
No idea, im just running csgo
