### ISSUE TITLE
Login not found

### ISSUE THREAD

**Issue by Nomad7** [dgibbs64/hlsw-fixes#20]
I suspect this may not be an issue you can solve, but it seems hlsw.org is no longer sending out registration emails and I am unable to launch the application without logging in. Is it possible to bypass, redirect, or otherwise circumvent the login requirement?

**Comment by dgibbs64** [comment]
you done need to login there is an option to skip login

**Comment by Nomad7** [comment]
Oh goodness, you're right, I just need to click Offline. I'm sorry for wasting your time. Thanks for the work you've done!
