### ISSUE TITLE
Timingout

### ISSUE THREAD

**Issue by Weeeishy** [dgibbs64/hlsw-fixes#5]
Hello,

I'm using your FIX for HLSW, however my servers are still timing out. Is there any workaround for that? It's for CSGO.

Thank you!

**Comment by dgibbs64** [comment]
Probably an issue with your query port. Try other servers do they work?

**Comment by Weeeishy** [comment]
Thanks for the prompt response!

I'm running 6 servers and they like timeout every 30-60 once. Also get log (internet) and (LAN) aren't working, I always get that error.

https://gyazo.com/9f19270f0af9708a42004a0b3d450794
