### ISSUE TITLE
It's not really a issue with hlsw is more of a issue with the website

### ISSUE THREAD

**Issue by ReportMe** [dgibbs64/hlsw-fixes#6]
Hello, How are you today? okay So I'm having a issue with your website. Somehow I forgot my password. so when I click on forgot password I this happens    http://hlsw.org/myhlsw/lost_password/
Not sure if it's my end or not. I have tried firefox, google chrome, opera, I even used my cell phone same issue. 
The hlsw.org page isn’t working

hlsw.org is currently unable to handle this request.
HTTP ERROR 500

**Comment by dgibbs64** [comment]
I do not run hlsw.org it is the official website. hlsw-fixes is an unofficial patch. The team behind HLSW no longer develop it or maintain the website so there is no way to login
